version: "3.9"

services:
  checkers:
    image: checkers-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - "io"
    ports:
      - "8080:8080"
    stdin_open: true
    container_name: checkers-container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: 192.168.1.135:0.0
      CHECKERS_SERVICE_HOST: checkers
      CHECKERS_SERVICE_PORT: 8080
      FILEIO_SERVICE_HOST: io
      FILEIO_SERVICE_PORT: 8081